### ISSUE TITLE
Link color Issue

### ISSUE THREAD

**Issue by T4H5iN** [ElijahPepe/BetterDiscordAddons#4]
![image](https://user-images.githubusercontent.com/77932280/114269275-e9b09d00-9a27-11eb-9039-320f8e69eeef.png)
All text and link looks like the same. So its hard to keep track of links. But when I got to edit it looks awesome.
![image](https://user-images.githubusercontent.com/77932280/114269290-12d12d80-9a28-11eb-9cee-8359455e765a.png)
So it would be great if links look like the picture above (when I got to edit)

Thank you!!

**Comment by ElijahPepe** [comment]
https://github.com/ElijahPepe/BetterDiscordAddons/issues/3#issuecomment-841765443
