### ISSUE TITLE
Guild names not showing

### ISSUE THREAD

**Issue by prun3** [ElijahPepe/BetterDiscordAddons#5]
when hovering over guilds you can still see the usual name popout, but its just one solid color.
Im not sure if the rgb code for text is the same as guild popout but its really my only guess as emotes in a guild-name still show on the popout. 

![image](https://user-images.githubusercontent.com/70281012/135286331-370fd17e-74c5-4eb7-be84-37a473a683de.png)

**Comment by ElijahPepe** [comment]
The issue was fixed but can't be pushed automatically so you'll have to reinstall the theme.

**Comment by prun3** [comment]
all good. thank you!
